candidate:
  name:
    first: "Chandan"
    middle: "Krishna"
    last: "Yalavarthy"

  education:
    highest_degree:
      degree: "M.S."
      field: "Computer Software Engineering"
      university: "Arizona State University"
      graduation:
        month: 5
        year: 2026

  profiles:
    email: "chandankrishna.y@gmail.com"
    phone: "+1 4808037754"
    linkedin: "www.linkedin.com/in/krishna-chandan"
    github: "https://github.com/YCK72"
    portfolio: ""

  location:
    address: "2125 E Apache Blvd"
    city: "Tempe"
    state: "Arizona"
    postal_code: "85281"
    country: "United States"

  preferences:
    willing_to_relocate: true
    remote: true
    hybrid: true
    onsite: true

  resumes:
    master_cv: "data/resumes/master_cv.pdf"
    sde: "data/resumes/sde_resume.pdf"
    ai_ml: "data/resumes/aiml_resume.pdf"
    data_science: "data/resumes/data_science_resume.pdf"
    it: "data/resumes/it_resume.pdf"